
import {IComponent, INITIAL_COMPONENT_STATE} from './component.vm';

export interface IComplexAsset
{
  Id:string;
  ComplexAssetId:string;
  ComplexAssetName:string;
  LastModified:Date;
  IsAssetIdAutoGenerated:boolean;
  AssetIdAutoIdPrefix:string;
  ComplexAssetCategoryId:string;
  ComplexAssetCategory:string
  ComplexAssetCategoryLabel:string;
  IsAssetCategoryAutoGenerated:boolean,
  Components:IComponent[]
}

export const INITIAL_COMPLEX__SPLIT_STATE:IComplexAsset={

  Id:undefined,
  ComplexAssetId:'',
  ComplexAssetName:'',
  LastModified:undefined,
  IsAssetIdAutoGenerated:false,
  AssetIdAutoIdPrefix:'',
  ComplexAssetCategoryId:undefined,
  ComplexAssetCategory:'',
  ComplexAssetCategoryLabel:'',
  IsAssetCategoryAutoGenerated:false,
  Components:[INITIAL_COMPONENT_STATE]
}












