import {IDimension, INITIAL_DIAMENSION_STATE} from './dimension.vm';
export interface IComponent
{
  Id:string;
  ComplexAssetId:string;
  ComponentTypeId:string;
  ComponentTypeName:string;
  ComponentTypeLabel:string;
  IdGeneratorTemplateId:number;
  AutoGeneratedPrefix:string;
  UseAutoGeneratedId:boolean;
  ComponentId:string;
  ComponentName:string;
  NetworkMeasureTypeId:number;
  NetworkMeasureType:string;
  DIUnitId:number;
  UnitName:string;
  FinanceSubClassId:number;
  FinanceSubClassName:string;
  LastModifiedDate:Date;
  Dimensions:IDimension[]

}

export const INITIAL_COMPONENT_STATE:IComponent={

  Id:undefined,
  ComplexAssetId:undefined,
  ComponentTypeId:undefined,
  ComponentTypeName:'',
  ComponentTypeLabel:'',
  IdGeneratorTemplateId:undefined,
  AutoGeneratedPrefix:'',
  UseAutoGeneratedId:false,
  ComponentId:undefined,
  ComponentName:'',
  NetworkMeasureTypeId:undefined,
  NetworkMeasureType:'',
  DIUnitId:undefined,
  UnitName:'',
  FinanceSubClassId:undefined,
  FinanceSubClassName:'',
  LastModifiedDate:undefined,
  Dimensions: [INITIAL_DIAMENSION_STATE]
}
