
export const complexAssetData:{}={

  Success:true,
  Reason:"",
  WorkOrderAttachments:"",
  ComponentNetWorkTypeIncomplete:"",
  Asset:{
    Id:"32370bb1-e26d-e611-bf0b-b00594ea8f26",
    ComplexAssetId:"A12809",
    IsAssetIdAutoGenerated:true,
    AssetIdAutoIdPrefix:"PLT",
    ComplexAssetName:"PSBE08_PTF01",
    LastModified:"2017-04-09T11:19:25",
    ComplexAssetCategoryId:"d48ff415-f4d7-4605-a416-6b2f265b20d9",
    ComplexAssetCategory:"AccessPlatforms",
    ComplexAssetCategoryLabel:"Access Platforms",
    IsAssetCategoryAutoGenerated:true,
    Components:[
      {
        Id:"8ed6bef0-dfae-e611-946c-06edd62954d7",
        ComplexAssetId:"32370bb1-e26d-e611-bf0b-b00594ea8f26",
        ComponentTypeId:"ca35e210-9e7f-45b1-9d08-a12cd358022e",
        ComponentTypeName:null,
        ComponentTypeLabel:null,
        IdGeneratorTemplateId:0,
        AutoGeneratedPrefix:null,
        UseAutoGeneratedId:false,
        ComponentId:"CP00014353",
        ComponentName:"Main",
        NetworkMeasureTypeId:2,
        NetworkMeasureType:"Length",
        DIUnitId:1,
        UnitName:"Metre",
        FinanceSubClassId:77,
        FinanceSubClassName:"Non Financial",
        LastModifiedDate:"0001-01-01T11:00:00",
        Dimensions:[
          {
            DimensionId:"b97b38fc-e1ae-e611-946c-06edd62954d7",
            NetworkMeasureTypeId:2,
            NetworkMeasureType:"Length",
            ComponentId:"8ed6bef0-dfae-e611-946c-06edd62954d7",
            UnitId:1,
            UnitName:"Metre",
            ShapeId:null,
            ShapeName:"",
            Measure:1.0000,
            RecordType:1,
            Multiplier:1.0000,
            Comment:null
          }
        ]
      }
    ]
  }
}













